<!-- GitHub Star -->
<a class="github-button" href="https://github.com/aui/art-template" data-count-href="/aui/art-template/stargazers" data-count-api="/repos/aui/art-template#stargazers_count" data-count-aria-label="# stargazers on GitHub" aria-label="Star aui/art-template on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/aui/art-template/fork" data-count-href="/aui/art-template/network" data-count-api="/repos/aui/art-template#forks_count" data-count-aria-label="# forks on GitHub" aria-label="Fork aui/art-template on GitHub">Fork</a>